project:
  type: website
  output-dir: docs
  
website:
  title: "Haley Mai"
  navbar:
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/haley5100/haley
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Haley Mai"

format:
  html:
    theme: Minty
    toc: true

editor: source

